language: c
compiler:
  - gcc
  - clang
# Change this to your needs
#script: ./configure && make
install: 
  - wget http://cython.org/release/Cython-0.20.2.tar.gz
  - tar -xzvf Cython-0.20.0.tar.gz
  - cd Cython-0.20.0 && python setup.py install
script: make clean && make