os:
  - linux
  - osx
language: c
compiler:
  - gcc
  - clang
# Change this to your needs
#script: ./configure && make
install:
  - sudo easy_install --find-links=https://github.com/msabramo/cython/releases/tag/0.19.1 Cython
  - sudo easy_install networkx
  #- sudo easy_install Cython
  - python -c 'import Cython; print (Cython)'
script:
  - export ARCHFLAGS='-Wno-error=unused-command-line-argument-hard-error-in-future'     
  - make clean && make
